import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { HomeHeader } from "./(components)/home-header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="h-screen w-screen overflow-hidden">
                <HomeHeader />
                <div className="h-full w-full pt-[3.5rem]">{children}</div>
            </body>
        </html>
    );
}
